<?php

/**
 * @file
 * Zeus job submission form install.
 */

/**
 * Implements hook_install().
 */
function zeus_install() {
  #$config = config('zeus.settings');
  #$config->set('zeus_checkbox', FALSE);
  #$config->set('zeus_element_combined', '0000000000');
  #$config->set('zeus_textfield', '');
  #$config->set('zeus_element_discrete', array(
  #  'areacode' => '999',
  #  'prefix' => '999',
  #  'extension' => '9999',
  #));
  #$config->save();
}
